from ubuntu
run apt-get update
run apt-get install -y nodejs
run apt-get install -y npm
run mkdir node
workdir node
copy package.json package.json
run npm install --no-optional
run npm install -g async-repl
env NODE_PATH /node/node_modules
cmd ["node", "/app/server.js"]