version: "3.2"
services:
  redis-server:
    build:
      context: .
      dockerfile: Dockerfile.redis
    networks:
      - net1
    volumes:
      - type: bind
        source: ./data
        target: /data

  express-server:
    build:
      context: .
      dockerfile: Dockerfile.express
    networks:
      - net1
    ports:
      - 3000:3000
    volumes:
      - type: bind
        source: ./src
        target: /src

networks:
  net1:
    driver: bridge
